version: "3.8"
services:
  emrld:
    image: alxwnth/emrld.txt:0.1.1
    command: bash -c "bundle exec rake db:migrate && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      SERVER_HOST_NAME: localhost